modLoader="javafml"
loaderVersion="[38,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/moltenwolfcub/playtime-mod/issues"
showAsResourcePack=false

[[mods]]
modId="playtime"
version="1.18.1-0.0.0"
displayName="Playtime"
displayURL="https://github.com/moltenwolfcub/playtime-mod"
logoFile="logo.png"
credits="Made by MoltenWolfCub"
authors="MoltenWolfCub"
description='''
All the playtime and party fun.
'''

[[dependencies.playtime]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.playtime]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
