modLoader="javafml"
loaderVersion="[38,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/moltenwolfcub/playtime-mod/issues"
showAsResourcePack=false

[[mods]]
modId="playtime"
version="1.0.0.0"
displayName="Playtime"
displayURL="https://github.com/moltenwolfcub/playtime-mod"
logoFile="logo.png"
credits="Made by me, MoltenWolfCub, alone"
authors="MoltenWolfCub"
description='''
All the fun in one mod.
'''
